### PR TITLE
Co-teaching episode draft

### PR DESCRIPTION
**Pull request by stepas-toliautas**
Relevant questions:
- Is this supposed to cover all of co-teaching or just contact team-teaching, covered in [CR manual](https://coderefinery.github.io/manuals/team-teaching/)?
- Is it OK to refer to the above-mentioned manual section or it's preferable to mine/ summarize it in the episode?
- What level of depth is envisioned? Since the episode is ~30 min, that would determine whether we add a practical exercise, a discussion on a certain question or leave it out altogether.

### CODE REVIEW

**Comment by samumantha** [comment]
Yay, thank you for getting this started 🔥

Own opinions about the questions: 

Yes, please refer to manuals where appropriate. We are also checking and updating manuals at the moment, so if there is something missing or outdated, now would be the perfect time to point it out. 

About covering all: I'd say no, but it can cover more than previous materials or the manuals.

About depth: where possible I'd prefer exercise/discussion over 'lecturing' ; since we have everyone sign up to separate sessions we also have the possibility to ask them to do some pre-task, eg reading the manuals page or some article or watch a video. 

For co-teaching episode, maybe we could let them watch short snippets of different examples of how co-teaching can go, from different recordings? Ie developing the take-home message themselves by discussing benefits/challenges of different approaches or so?

**Comment by bast** [comment]
I would also prefer summary + discussion/exercise over only-lecture format. Perhaps it would be effective to present co-teaching in a co-teaching format?

Referring to manuals is good but I personally like if the material is self-contained. It does not need to repeat what is in the manual but maybe it can summarize it in a self-contained way. But this is not a requirement, just my personal preference.

**Comment by samumantha** [comment]
We can also adjust the timing for the episodes on day 2, if you have a good exercise that needs more time.

**Comment by bast** [comment]
Thanks a lot for your work! I merge and we improve with subsequent pull requests?

**Pull request merged**
