### PR TITLE
Co-teaching episode update

### PR DESCRIPTION
**Pull request by stepas-toliautas**
It would be great to expand on the last hint, why and how not every learner might like the team-taught lessons.

### CODE REVIEW

**Comment by bast** [comment]
I will now review and add something about that point.

**Comment by bast** [comment]
This part I don't follow: "Open-source material and joint planning allows the lessons to be held in parallel (at the same time) or alternatively (at different times or with minor adjustments for the target audience)".

**Comment by bast** [comment]
> "While in breakout rooms, read about one of the two basic team-teaching models presented in the CodeRefinery manual and discuss"

I recommend to not ask participants to read some material during the short 10 minutes. Instead we should give them a concrete list of questions to discuss and use the 10 minutes for discussion and writing down conclusions.

**Review by bast — APPROVED** [review]
Thanks for the work! I added my changes. It can be merged but I recommend to address somehow the two points raised. But we can also fix it after it is merged if you prefer that.

**Comment by stepas-toliautas** [comment]
- I clarified the co-teaching variants section -- the bullet in question is about one form that's co-teaching, but not team teaching.
- As I'd like the learners to think about team teaching models, the continuum, and already how to apply it in practice, I added summaries of the two models for us to present.

**Comment by bast** [comment]
Thank you so much!

**Pull request merged**
