### PR TITLE
First lesson template draft based on RD and RB comments

### PR DESCRIPTION
**Pull request by samumantha**
Co-authored-by @bast 
Co-authored-by @rkdarst

Relates  to #74 #85

### CODE REVIEW

**Comment by samumantha** [comment]
What do you think about the exercise?

Do we have documentation about the lesson template somewhere, or the cr sphinx extension?

**Comment by bast** [comment]
I like the exercise! Later we can add a solution.

**Comment by samumantha** [comment]
Ups, the co-authoring needs the email address not the github name, I forgot; sorry!

**Comment by bast** [comment]
> Ups, the co-authoring needs the email address not the github name, I forgot; sorry!

For email you can use bast@users.noreply.github.com and corresponding.

**Comment by rkdarst** [comment]
For the exercise we could recommend a lesson to clone and build, trying to edit things. (The "time to first preview" may be a good measure?)  I can also add after merging this.

**Comment by rkdarst** [comment]
What would be a good sample project to clone?  maybe the template?

https://coderefinery.github.io/sphinx-lesson-template/

As part of this we could do a bulk convert to MyST-MD so it looks more normal to people:
https://rst-to-myst.readthedocs.io/en/stable/index.html
https://docs.readthedocs.io/en/stable/guides/migrate-rest-myst.html

**Comment by bast** [comment]
+1 for using MyST-Markdown instead of a mix of Markdown and RST.

**Comment by samumantha** [comment]
Another plus one for just focusing on markdown. 

For the exercise I thought of making it close to real life as possible. Ie you find the template, but how to now start using it to create your own lesson. 
This (including the questions) will also teach everything necessary to know to contribute to already existing lessons.

But we can of course also mention something specific to contributing in the materials.

**Comment by samumantha** [comment]
> What would be a good sample project to clone? maybe the template?
> 
> https://coderefinery.github.io/sphinx-lesson-template/
> 
> As part of this we could do a bulk convert to MyST-MD so it looks more normal to people: https://rst-to-myst.readthedocs.io/en/stable/index.html https://docs.readthedocs.io/en/stable/guides/migrate-rest-myst.html

Will you do this bulk convert @rkdarst  ?

**Comment by samumantha** [comment]
I'll merge this for now, to have the draft in materials, made a new issue for the conversion

We can continue developing this into actual materials in follow ups.

**Pull request merged**
