### PR TITLE
A first draft for overview and onboarding episode

### PR DESCRIPTION
**Pull request by samumantha**
@rkdarst @dhanyapushpadas @stepas-toliautas 

What do you think about the structure? 
Any ideas for fun exercises/discussions?

Related #73 ; 
regarding #87  and #86

### CODE REVIEW

**Comment by samumantha** [comment]
At coordinator @bast : Should this episode introduce more any of the topics following on that day?

**Comment by samumantha** [comment]
Should we also merge this and then go from there?

**Comment by bast** [comment]
Yes please. "Something is better than nothing" to get people to contribute and iterate on text.

**Comment by samumantha** [comment]
Ok, please merge :)
Let's collect thoughts on improvements for the different lessons in the issues

**Pull request merged**
